export const MenuData = [
  // Coffee
  {
    id: 1,
    price: 2500,
    title: "Espresso",
    desc: "Strong and rich espresso shot",
    img: require("./../../assests/menu/Coffee/coffee-1.png"),
    category: "Coffee",
  },
  {
    id: 2,
    price: 2000,
    title: "Filter Coffee",
    desc: "Freshly brewed filter coffee",
    img: require("./../../assests/menu/Coffee/coffee-2.png"),
    category: "Coffee",
  },
  {
    id: 3,
    price: 2500,
    title: "Americano",
    desc: "Espresso with hot water",
    img: require("./../../assests/menu/Coffee/coffee-3.png"),
    category: "Coffee",
  },
  {
    id: 4,
    price: 3000,
    title: "Turkish Coffee",
    desc: "Traditional Turkish coffee",
    img: require("./../../assests/menu/Coffee/coffee-4.png"),
    category: "Coffee",
  },
  {
    id: 5,
    price: 3500,
    title: "Café au Lait",
    desc: "Coffee with steamed milk",
    img: require("./../../assests/menu/Coffee/coffee-5.png"),
    category: "Coffee",
  },
  {
    id: 6,
    price: 3000,
    title: "Cappuccino",
    desc: "Espresso with milk foam",
    img: require("./../../assests/menu/Coffee/coffee-6.png"),
    category: "Coffee",
  },
  {
    id: 7,
    price: 3500,
    title: "Caramel Coffee",
    desc: "Coffee with caramel flavor",
    img: require("./../../assests/menu/Coffee/coffee-7.png"),
    category: "Coffee",
  },
  {
    id: 8,
    price: 3500,
    title: "Hazelnut Coffee",
    desc: "Coffee with hazelnut flavor",
    img: require("./../../assests/menu/Coffee/coffee-8.png"),
    category: "Coffee",
  },
  {
    id: 9,
    price: 3500,
    title: "Chocolate Coffee",
    desc: "Coffee with chocolate flavor",
    img: require("./../../assests/menu/Coffee/coffee-9.png"),
    category: "Coffee",
  },
  {
    id: 10,
    price: 3000,
    title: "Iced Coffee",
    desc: "Cold and refreshing coffee",
    img: require("./../../assests/menu/Coffee/coffee-10.png"),
    category: "Coffee",
  },
  // Tea
  {
    id: 11,
    price: 2500,
    title: "Green Tea",
    desc: "Healthy and refreshing green tea",
    img: require("./../../assests/menu/Tea/tea-1.png"),
    category: "Tea",
  },
  {
    id: 12,
    price: 3000,
    title: "Mint Tea",
    desc: "Fresh mint-infused tea",
    img: require("./../../assests/menu/Tea/tea-2.png"),
    category: "Tea",
  },
  {
    id: 13,
    price: 3000,
    title: "Almond Tea",
    desc: "Tea infused with almond flavor",
    img: require("./../../assests/menu/Tea/tea-3.png"),
    category: "Tea",
  },
  {
    id: 14,
    price: 3500,
    title: "Pine Nut Tea",
    desc: "Tea topped with pine nuts",
    img: require("./../../assests/menu/Tea/tea-4.png"),
    category: "Tea",
  },
  {
    id: 15,
    price: 5000,
    title: "Baklava Tea",
    desc: "Sweet tea inspired by baklava flavors",
    img: require("./../../assests/menu/Tea/tea-5.png"),
    category: "Tea",
  },
  // Juices & Cocktails
  {
    id: 16,
    price: 3500,
    title: "Lemonade",
    desc: "Fresh and zesty homemade lemonade",
    img: require("./../../assests/menu/Juices/juice-1.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 17,
    price: 5000,
    title: "Strawberry Juice",
    desc: "Sweet and refreshing strawberry juice",
    img: require("./../../assests/menu/Juices/juice-2.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 18,
    price: 4500,
    title: "Orange Juice",
    desc: "Freshly squeezed orange juice",
    img: require("./../../assests/menu/Juices/juice-3.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 19,
    price: 5000,
    title: "Banana Juice",
    desc: "Smooth and creamy banana juice",
    img: require("./../../assests/menu/Juices/juice-4.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 20,
    price: 6000,
    title: "Kiwi Juice",
    desc: "Tangy and refreshing kiwi juice",
    img: require("./../../assests/menu/Juices/juice-5.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 21,
    price: 7000,
    title: "Cocktail Juice",
    desc: "Mixed fruit juice cocktail",
    img: require("./../../assests/menu/Juices/juice-6.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 22,
    price: 8000,
    title: "Milkshake",
    desc: "Creamy milkshake with your choice of flavor",
    img: require("./../../assests/menu/Juices/juice-7.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 23,
    price: 6000,
    title: "Hot Chocolate",
    desc: "Rich and comforting hot chocolate",
    img: require("./../../assests/menu/Juices/juice-8.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 24,
    price: 5000,
    title: "Eggnog",
    desc: "Classic creamy eggnog",
    img: require("./../../assests/menu/Juices/juice-9.jpg"),
    category: "Juices & Cocktails",
  },
  {
    id: 25,
    price: 7000,
    title: "Mojito",
    desc: "Refreshing mint and lime mojito",
    img: require("./../../assests/menu/Juices/juice-10.jpg"),
    category: "Juices & Cocktails",
  },
  // Ice Cream
  {
    id: 18,
    price: 5000,
    title: "2 Scoops",
    desc: "Two scoops of ice cream",
    img: require("./../../assests/menu/Ice/icecream-1.jpg"),
    category: "Ice Cream",
  },
  {
    id: 19,
    price: 6000,
    title: "3 Scoops",
    desc: "Three scoops of ice cream",
    img: require("./../../assests/menu/Ice/icecream-2.jpg"),
    category: "Ice Cream",
  },
  {
    id: 20,
    price: 8000,
    title: "Special Ice Cream",
    desc: "Deluxe ice cream selection",
    img: require("./../../assests/menu/Ice/icecream-3.jpg"),
    category: "Ice Cream",
  },
  // Pastries
  {
    id: 26,
    price: 5000,
    title: "Cakes",
    desc: "Delicious and fluffy assorted cakes",
    img: require("./../../assests/menu/Pastries/pastries-1.jpg"),
    category: "Pastries",
  },
  {
    id: 27,
    price: 7000,
    title: "Fondant",
    desc: "Rich chocolate fondant with a molten center",
    img: require("./../../assests/menu/Pastries/pastries-2.jpg"),
    category: "Pastries",
  },
  {
    id: 28,
    price: 6500,
    title: "Chocolate Mousse",
    desc: "Smooth and creamy chocolate mousse",
    img: require("./../../assests/menu/Pastries/pastries-3.jpg"),
    category: "Pastries",
  },
  {
    id: 29,
    price: 7000,
    title: "Tiramisu",
    desc: "Classic Italian dessert with mascarpone and coffee",
    img: require("./../../assests/menu/Pastries/pastries-4.jpg"),
    category: "Pastries",
  },
  {
    id: 30,
    price: 8000,
    title: "Cheesecake",
    desc: "Creamy cheesecake with a biscuit crust",
    img: require("./../../assests/menu/Pastries/pastries-5.jpg"),
    category: "Pastries",
  },
  {
    id: 31,
    price: 2000,
    title: "Croissant",
    desc: "Flaky and buttery French croissant",
    img: require("./../../assests/menu/Pastries/pastries-6.jpg"),
    category: "Pastries",
  },
  {
    id: 32,
    price: 4000,
    title: "Classic Cake",
    desc: "Soft and moist classic cake",
    img: require("./../../assests/menu/Pastries/pastries-7.jpg"),
    category: "Pastries",
  },
  {
    id: 33,
    price: 6500,
    title: "Chocolate Cake",
    desc: "Decadent chocolate cake with rich frosting",
    img: require("./../../assests/menu/Pastries/pastries-8.jpg"),
    category: "Pastries",
  },
  {
    id: 34,
    price: 5000,
    title: "Waffles",
    desc: "Crispy waffles served with toppings of your choice",
    img: require("./../../assests/menu/Pastries/pastries-9.jpg"),
    category: "Pastries",
  },
  // Crepes
  {
    id: 35,
    price: 5000,
    title: "Sweet Crepe",
    desc: "Deliciously sweet crepe with sugar and toppings",
    img: require("./../../assests/menu/Crepes/crepes-1.jpg"),
    category: "Crepes",
  },
  {
    id: 36,
    price: 6000,
    title: "Chocolate Crepe",
    desc: "Crepe filled with rich chocolate",
    img: require("./../../assests/menu/Crepes/crepes-2.jpg"),
    category: "Crepes",
  },
  {
    id: 37,
    price: 7000,
    title: "Nutella Crepe",
    desc: "Crepe filled with Nutella and other sweet toppings",
    img: require("./../../assests/menu/Crepes/crepes-3.jpg"),
    category: "Crepes",
  },
  {
    id: 38,
    price: 6500,
    title: "Oreo Crepe",
    desc: "Crepe filled with crushed Oreos and cream",
    img: require("./../../assests/menu/Crepes/crepes-4.jpg"),
    category: "Crepes",
  },
  {
    id: 39,
    price: 5500,
    title: "Cheese Crepe",
    desc: "Savory crepe filled with melted cheese",
    img: require("./../../assests/menu/Crepes/crepes-5.jpg"),
    category: "Crepes",
  },
  {
    id: 40,
    price: 6000,
    title: "Tuna Crepe",
    desc: "Savory crepe filled with tuna and vegetables",
    img: require("./../../assests/menu/Crepes/crepes-6.jpg"),
    category: "Crepes",
  },
  // Extras
  {
    id: 41,
    price: 1500,
    title: "Half Liter Water",
    desc: "Refreshing half liter bottle of water",
    img: require("./../../assests/menu/Extras/extras-1.jpg"),
    category: "Extras",
  },
  {
    id: 42,
    price: 2500,
    title: "1 Liter Water",
    desc: "Refreshing 1 liter bottle of water",
    img: require("./../../assests/menu/Extras/extras-2.jpg"),
    category: "Extras",
  },
  {
    id: 43,
    price: 10000,
    title: "Shisha",
    desc: "Traditional shisha for a relaxing experience",
    img: require("./../../assests/menu/Extras/extras-3.jpg"),
    category: "Extras",
  },
];
